# 配置工程目录
[projectpath]
path_data = ./data/
path_imgs = ./imgs/
path_util = /Users/apple/Works/project/stock/util

# 数据源token
[datatoken]
token_zhitu = DE9D18E1-D6B2-41AA-9F87-D9908AD2F5D1
token_tushare = bc3439516f386aa5dade311bbd1b0d2c3e1109fa98648bcab1801803

# 数据源url
[datasource]
url_zhitu = 
url_tushare = 
url_akshare = 
url_tencent = https://proxy.finance.qq.com/cgi/cgi-bin/stockinfoquery/kline/app/get?code=
